server:
  port: 8080

spring:
  application:
    name: user-management-backend

  data:
    mongodb:
      uri: mongodb://localhost:27017/user_management_db

logging:
  level:
    org.springframework: INFO
    com.chatgpt: DEBUG